version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - mvn clean install -DskipTests=true

  build:
    commands:
      - echo Building the application...
      - mvn package

artifacts:
  files:
    - target/*.jar

