version: 0.2
phases:
 build:
  commands: 
  - mvn clean install
 post_build:
  commands:
  - mv target/HotelReservationApplication-0.0.1-SNAPSHOT.jar HotelReservationApplication-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - HotelReservationApplication-0.0.1-SNAPSHOT.jar
